### PR TITLE
Fix exports of functions removed from Base in 0.7.0-DEV.602

### LINKED ISSUE #174: Base DSP functions are not exported
Ref. https://github.com/JuliaLang/julia/pull/21956#issuecomment-331141107.

E.g.:
```julia
julia> VERSION
v"0.7.0-DEV.1776"

julia> Pkg.status("DSP")
 - DSP                           0.3.2

julia> :xcorr in names(DSP)
false

julia> :xcorr in names(DSP, true)
true
```

### PR DESCRIPTION
**Pull request by martinholters**
Fixes #174.

### CODE REVIEW

File: test/filt_stream.jl [hunk 1]
```diff
@@ -12,7 +12,7 @@ function naivefilt(h::Vector, x::Vector, resamplerate::Rational=1//1)
         xZeroStuffed[n*upfactor+1] = x[n+1]
     end
 
-    y = Base.filt(h, one(eltype(x)), xZeroStuffed)
```
Comment (martinholters) [inline test/filt_stream.jl]: What was the intention of the `Base` qualification anyway? Has `DSP.filt` ever been a separate function, not just additional methods to `Base.filt`?

**Comment by ararslan** [comment]
Excellent, thanks for fixing this!
