### PR TITLE
Fix #211

### LINKED ISSUE #211: resampling/filtering don't accept integer resampling rates
The resampling rate arguments for `FIRFilter` and `resample` accept `Rational` and `AbstractFloat`, but not integers.

```julia
julia> x = rand(8)
8-element Array{Float64,1}:
 0.179779
...

julia> resample(x, 2)
ERROR: MethodError: no method matching resample_filter(::Int64)
Closest candidates are:
  resample_filter(::AbstractFloat) at C:\Users\sfr\.julia\v0.6\DSP\src\Filters\design.jl:594
  resample_filter(::AbstractFloat, ::Any) at C:\Users\sfr\.julia\v0.6\DSP\src\Filters\design.jl:594
  resample_filter(::AbstractFloat, ::Any, ::Any) at C:\Users\sfr\.julia\v0.6\DSP\src\Filters\design.
jl:594
  ...
Stacktrace:
 [1] resample(::Array{Float64,1}, ::Int64) at C:\Users\sfr\.julia\v0.6\DSP\src\Filters\stream_filt.j
l:706
 [2] macro expansion at C:\Users\sfr\.julia\v0.6\Atom\src\repl.jl:118 [inlined]
 [3] anonymous at .\<missing>:?

julia> resample(x, 2//1)
15-element Array{Float64,1}:
 0.179762
...
```

### PR DESCRIPTION
**Pull request by jordancluts**
Intended to fix #211 by simply changing the accepted type signature where needed.

### CODE REVIEW

**Comment by jordancluts** [comment]
I believe the failed test will be fixed by #216

File: src/Filters/stream_filt.jl [hunk 1]
```diff
@@ -58,7 +58,7 @@ end
 # Rational resampler FIR kernel
 mutable struct FIRRational{T}  <: FIRKernel{T}
     pfb::PFB{T}
-    ratio::Rational{Int}
```
Comment (martinholters) [inline src/Filters/stream_filt.jl]: Moving away from a concrete type here might have a performance impact, though I haven't checked where `ratio` is used/how large the impact is. Alternatively, we could leave this as `Rational{Int}` and convert upon construction, no?

**Comment by martinholters** [comment]
Can you add tests exercising the integer case?

**Comment by jordancluts** [comment]
I'll give it a try, I'm new and haven't tried doing anything with testing before but it should be easy enough to crib off of the test_rational in filt_stream.jl

**Comment by jordancluts** [comment]
Could someone take a look at the latest rendition here?

File: test/filt_stream.jl [hunk 2]
```diff
@@ -354,4 +408,7 @@ end
             test_arbitrary(Th, x, convert(Float64, ratio)+rand(), 32)
         end
     end
+    if numerator(ratio) == interpolation && denominator(ratio) == decimation && numerator(ratio) != 1 && denominator(ratio) == 1
```
Comment (ssfrr) [inline test/filt_stream.jl]: Could this just be `if decimation == 1` ?

File: test/filt_stream.jl [hunk 3]
```diff
@@ -275,6 +275,60 @@ function test_rational(h, x, ratio)
 end
 
 
+#
+# Integer resampling
+#
+
+function test_integer(h, x, ratio)
```
Comment (ssfrr) [inline test/filt_stream.jl]: It seems like the `test_xxx` functions are almost identical and could be combined into a single `test_resampling` function. Having a bunch of these almost-identical functions makes it hard to see what's actually different about the tests. This isn't strictly your problem because there's already quite a bit of duplication before this PR, but perhaps this is a good opportunity to try to refactor and clean up this testing. Would you be willing to take a crack at it?

I'd be happy to drop the big ASCII-art headings if that makes it easier to combine the functions. I don't know if anyone else is attached to them - maybe @simonster?

File: test/filt_stream.jl (hunk 2 above)
Comment (jordancluts) [reply test/filt_stream.jl]: I believe you are right here. I couldn't figure out what the `numerator(ratio)==interpolation && denominator(ratio == decimation` was for in the test_rational if statement so I left them in case I was simply not understanding the purpose.

File: test/filt_stream.jl (hunk 3 above)
Comment (jordancluts) [reply test/filt_stream.jl]: It'd be very easy to combine the rational resampling and integer resampling (the rational resampling needs I think 1 change to run the integer tests). I had separated them because that seemed to be how the rest of the test functions were structured. I will edit this PR to reduce the additions. Refactoring all the tests is a bit beyond me. I'm trying to get my feet wet with my first PR here and I don't really understand all the testing machinery. I spent awhile looking at the tests and they have so much similarity there has to be was to reduce code duplication but I'm not sure how to go about it without obfuscating the process further or reducing code coverage. I also have a hard time prototyping a change as I'm not even sure how tests are run locally so I've been sort of manually testing the tests as it were.

Comment (ssfrr) [reply test/filt_stream.jl]: Yeah, that's reasonable. It's always a tough judgment call whether to duplicate for consistency, but the new version seems like a good balance - at least it's not making the duplication worse. :smile: 

I'll take a look tonight at the latest changes. I'll also see if I can figure out what's going on with all this `@timeifinteractive` stuff (it predates me working on this package). I usually just run the tests with `julia test/runtests.jl`.

Thanks for the contribution!

**Comment by ssfrr** [comment]
Looks good, I was going to make some minor tweaks (just removing some now-unnecessary `x//1`s that were converting ints to rationals), but AFAICT I don't have permission to push to this branch. Would you mind clicking the "allow maintainers to make changes to this PR" checkbox?

**Comment by jordancluts** [comment]
The "Allow edits from maintainers" box is already checked here. Is there somewhere else I need to grant permission?

**Comment by ssfrr** [comment]
Figured it out. It was trying to push to the wrong branch name on your fork. Once CI passes I'll merge.

**Comment by ssfrr** [comment]
merged! Thanks for the contribution.
